spring:
  application:
    name: defaultApp
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
logging:
  level:
    ROOT: INFO
org.springframework.cloud.config: DEBUG
